/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Controllers.TextPrompt;
import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Panel;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.plaf.basic.BasicPanelUI;

/**
 *
 * @author DELL
 */
public class HomeFrame extends javax.swing.JFrame {

    /**
    
     * Creates new form HomeFrame
     */
    private TextPrompt p;
    private ArrayList<JPanel>panels;
    private ArrayList<JButton>BtnList;
    public HomeFrame() {
        initComponents();
        LoadPanel();
        XuLiPanel(pnMain_);
        LoadButton();
        XuLiBtn();

        JPanel pn= new ProfileJPanel();
        pnQuanlynhansu.add(pn);
        pn.setVisible(true);
        p = new TextPrompt("Tìm Kiếm", txtTimkiemAn);
      this.btnTinnhan.setUI(new BasicButtonUI());
       this.btnThongbao.setUI(new BasicButtonUI());
       this.btnThoat.setUI(new BasicButtonUI());
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnMenu = new javax.swing.JPanel();
        pnCopyright = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnQuantri = new javax.swing.JButton();
        btnQuanlynhansu = new javax.swing.JButton();
        btnQuanlytuyendung = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnTrogiup = new javax.swing.JButton();
        pnPerson = new javax.swing.JPanel();
        btnLoout = new javax.swing.JButton();
        btnInfo = new javax.swing.JButton();
        btnSetting = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        lbLogoNhom = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        pnHead = new javax.swing.JPanel();
        btnThongbao = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        txtTimkiemAn = new javax.swing.JTextField();
        lbTimkiem = new javax.swing.JLabel();
        pnTimkiemHien = new javax.swing.JPanel();
        pnUser = new javax.swing.JPanel();
        lbName = new javax.swing.JLabel();
        jLabel_ = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnTinnhan = new javax.swing.JButton();
        pnMain = new javax.swing.JPanel();
        pnTrogiup = new javax.swing.JPanel();
        pnThongke = new javax.swing.JPanel();
        pnMain_ = new javax.swing.JPanel();
        pnQuantrihethong = new javax.swing.JPanel();
        pnQuanlynhansu = new javax.swing.JPanel();
        pnInfo = new javax.swing.JPanel();
        pnSetting = new javax.swing.JPanel();
        pnQuanlytuyendung = new javax.swing.JPanel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));
        setMinimumSize(new java.awt.Dimension(1360, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1600, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(242, 242, 242));
        pnMenu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnMenuMouseClicked(evt);
            }
        });
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("copyright@ 3MW");

        javax.swing.GroupLayout pnCopyrightLayout = new javax.swing.GroupLayout(pnCopyright);
        pnCopyright.setLayout(pnCopyrightLayout);
        pnCopyrightLayout.setHorizontalGroup(
            pnCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnCopyrightLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
        pnCopyrightLayout.setVerticalGroup(
            pnCopyrightLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCopyrightLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pnMenu.add(pnCopyright, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 660, 200, 50));

        btnQuantri.setBackground(new java.awt.Color(242, 242, 242));
        btnQuantri.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnQuantri.setForeground(new java.awt.Color(85, 85, 85));
        btnQuantri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/staff_48px.png"))); // NOI18N
        btnQuantri.setText("QUẢN TRỊ            ");
        btnQuantri.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnQuantri.setBorderPainted(false);
        btnQuantri.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnQuantriFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnQuantriFocusLost(evt);
            }
        });
        btnQuantri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuantriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuantriMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuantriMouseExited(evt);
            }
        });
        btnQuantri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuantriActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuantri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 60));

        btnQuanlynhansu.setBackground(new java.awt.Color(242, 242, 242));
        btnQuanlynhansu.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnQuanlynhansu.setForeground(new java.awt.Color(85, 85, 85));
        btnQuanlynhansu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Planes.PNG"))); // NOI18N
        btnQuanlynhansu.setText("QL NHÂN SỰ        ");
        btnQuanlynhansu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnQuanlynhansu.setBorderPainted(false);
        btnQuanlynhansu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnQuanlynhansuFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnQuanlynhansuFocusLost(evt);
            }
        });
        btnQuanlynhansu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanlynhansuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanlynhansuMouseExited(evt);
            }
        });
        btnQuanlynhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlynhansuActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanlynhansu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 200, 60));

        btnQuanlytuyendung.setBackground(new java.awt.Color(242, 242, 242));
        btnQuanlytuyendung.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnQuanlytuyendung.setForeground(new java.awt.Color(85, 85, 85));
        btnQuanlytuyendung.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/APs.PNG"))); // NOI18N
        btnQuanlytuyendung.setText("TUYỂN DỤNG        ");
        btnQuanlytuyendung.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnQuanlytuyendung.setBorderPainted(false);
        btnQuanlytuyendung.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnQuanlytuyendungFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnQuanlytuyendungFocusLost(evt);
            }
        });
        btnQuanlytuyendung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnQuanlytuyendungMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnQuanlytuyendungMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnQuanlytuyendungMouseExited(evt);
            }
        });
        btnQuanlytuyendung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuanlytuyendungActionPerformed(evt);
            }
        });
        pnMenu.add(btnQuanlytuyendung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 200, 60));

        btnThongke.setBackground(new java.awt.Color(242, 242, 242));
        btnThongke.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnThongke.setForeground(new java.awt.Color(85, 85, 85));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Dashboard.PNG"))); // NOI18N
        btnThongke.setText("THỐNG KÊ           ");
        btnThongke.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThongke.setBorderPainted(false);
        btnThongke.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnThongkeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnThongkeFocusLost(evt);
            }
        });
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongkeMouseExited(evt);
            }
        });
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });
        pnMenu.add(btnThongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 200, 60));

        btnTrogiup.setBackground(new java.awt.Color(242, 242, 242));
        btnTrogiup.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btnTrogiup.setForeground(new java.awt.Color(85, 85, 85));
        btnTrogiup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/ask_question_48px.png"))); // NOI18N
        btnTrogiup.setText("TRỢ GIÚP             ");
        btnTrogiup.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTrogiup.setBorderPainted(false);
        btnTrogiup.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnTrogiupFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnTrogiupFocusLost(evt);
            }
        });
        btnTrogiup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrogiupMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrogiupMouseExited(evt);
            }
        });
        btnTrogiup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrogiupActionPerformed(evt);
            }
        });
        pnMenu.add(btnTrogiup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 200, 60));

        pnPerson.setBackground(new java.awt.Color(242, 242, 242));
        pnPerson.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnPersonMouseClicked(evt);
            }
        });
        pnPerson.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLoout.setBackground(new java.awt.Color(242, 242, 242));
        btnLoout.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        btnLoout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/shut-down.png"))); // NOI18N
        btnLoout.setText("    LOGOUT                 ");
        btnLoout.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLoout.setBorderPainted(false);
        btnLoout.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnLooutFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnLooutFocusLost(evt);
            }
        });
        btnLoout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLooutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnLooutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnLooutMouseExited(evt);
            }
        });
        pnPerson.add(btnLoout, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 2, 196, 60));

        btnInfo.setBackground(new java.awt.Color(242, 242, 242));
        btnInfo.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        btnInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Membresia.PNG"))); // NOI18N
        btnInfo.setText(" PROFILE                     ");
        btnInfo.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnInfo.setBorderPainted(false);
        btnInfo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnInfoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnInfoFocusLost(evt);
            }
        });
        btnInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInfoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInfoMouseExited(evt);
            }
        });
        btnInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoActionPerformed(evt);
            }
        });
        pnPerson.add(btnInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 196, 60));

        btnSetting.setBackground(new java.awt.Color(242, 242, 242));
        btnSetting.setFont(new java.awt.Font("Times New Roman", 0, 10)); // NOI18N
        btnSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sync_settings_48px.png"))); // NOI18N
        btnSetting.setText("SETTING                     ");
        btnSetting.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSetting.setBorderPainted(false);
        btnSetting.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                btnSettingFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                btnSettingFocusLost(evt);
            }
        });
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
        });
        btnSetting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSettingActionPerformed(evt);
            }
        });
        pnPerson.add(btnSetting, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 196, 60));

        jPanel3.setBackground(new java.awt.Color(242, 242, 242));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/chevron_30px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(jLabel1)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnPerson.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 200, 30));

        jSeparator6.setBackground(new java.awt.Color(242, 242, 242));
        pnPerson.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 190, 2));

        jSeparator7.setBackground(new java.awt.Color(242, 242, 242));
        pnPerson.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 190, 10));

        jSeparator8.setBackground(new java.awt.Color(242, 242, 242));
        pnPerson.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 190, 2));

        pnMenu.add(pnPerson, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 240));

        lbLogoNhom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/logoUI.png"))); // NOI18N
        lbLogoNhom.setText("Logo");
        lbLogoNhom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbLogoNhomMouseClicked(evt);
            }
        });
        pnMenu.add(lbLogoNhom, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 190));
        pnMenu.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 590, 190, 10));
        pnMenu.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 190, 10));
        pnMenu.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 190, 10));
        pnMenu.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 190, 10));
        pnMenu.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 190, 10));

        getContentPane().add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 200, 838));

        pnHead.setBackground(new java.awt.Color(67, 142, 185));
        pnHead.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pnHeadMouseDragged(evt);
            }
        });
        pnHead.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnHeadMousePressed(evt);
            }
        });
        pnHead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThongbao.setBackground(new java.awt.Color(118, 44, 89));
        btnThongbao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/notification_25px.png"))); // NOI18N
        btnThongbao.setBorderPainted(false);
        btnThongbao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongbaoActionPerformed(evt);
            }
        });
        pnHead.add(btnThongbao, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 0, 50, 50));

        btnThoat.setBackground(new java.awt.Color(211, 60, 91));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/delete_25px.png"))); // NOI18N
        btnThoat.setBorderPainted(false);
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        pnHead.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 0, 50, 50));

        txtTimkiemAn.setBackground(new java.awt.Color(67, 142, 185));
        txtTimkiemAn.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        txtTimkiemAn.setForeground(new java.awt.Color(255, 255, 255));
        txtTimkiemAn.setToolTipText("");
        txtTimkiemAn.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtTimkiemAn.setOpaque(false);
        pnHead.add(txtTimkiemAn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 210, 25));

        lbTimkiem.setBackground(new java.awt.Color(0, 51, 204));
        lbTimkiem.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        lbTimkiem.setForeground(new java.awt.Color(255, 255, 255));
        lbTimkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/search_30px.png"))); // NOI18N
        pnHead.add(lbTimkiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 50, 30));

        javax.swing.GroupLayout pnTimkiemHienLayout = new javax.swing.GroupLayout(pnTimkiemHien);
        pnTimkiemHien.setLayout(pnTimkiemHienLayout);
        pnTimkiemHienLayout.setHorizontalGroup(
            pnTimkiemHienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnTimkiemHienLayout.setVerticalGroup(
            pnTimkiemHienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        pnHead.add(pnTimkiemHien, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, 2));

        pnUser.setBackground(new java.awt.Color(87, 158, 200));
        pnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnUserMouseExited(evt);
            }
        });

        lbName.setFont(new java.awt.Font("Segoe UI Light", 3, 14)); // NOI18N
        lbName.setForeground(new java.awt.Color(255, 255, 255));
        lbName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/clientes.png"))); // NOI18N
        lbName.setText("Le Tu Tuan");

        jLabel_.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/menu.png"))); // NOI18N

        javax.swing.GroupLayout pnUserLayout = new javax.swing.GroupLayout(pnUser);
        pnUser.setLayout(pnUserLayout);
        pnUserLayout.setHorizontalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnUserLayout.setVerticalGroup(
            pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnUserLayout.createSequentialGroup()
                .addGroup(pnUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbName, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        pnHead.add(pnUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        pnHead.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 2, 50));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        pnHead.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 35, 220, 2));

        btnTinnhan.setBackground(new java.awt.Color(44, 118, 89));
        btnTinnhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/facebook_messenger_25px.png"))); // NOI18N
        btnTinnhan.setBorderPainted(false);
        pnHead.add(btnTinnhan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1490, 0, 50, 50));

        getContentPane().add(pnHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1588, 50));

        pnMain.setBackground(new java.awt.Color(255, 255, 255));
        pnMain.setLayout(new java.awt.CardLayout());

        pnTrogiup.setBackground(new java.awt.Color(0, 204, 204));
        pnTrogiup.setLayout(new java.awt.CardLayout());

        pnThongke.setBackground(new java.awt.Color(255, 204, 51));
        pnThongke.setLayout(new java.awt.CardLayout());

        pnMain_.setBackground(new java.awt.Color(255, 255, 255));
        pnMain_.setLayout(new java.awt.CardLayout());

        pnQuantrihethong.setBackground(new java.awt.Color(153, 153, 255));
        pnQuantrihethong.setLayout(new java.awt.CardLayout());
        pnMain_.add(pnQuantrihethong, "card2");

        pnThongke.add(pnMain_, "card6");

        pnTrogiup.add(pnThongke, "card5");

        pnMain.add(pnTrogiup, "card6");

        pnQuanlynhansu.setBackground(new java.awt.Color(255, 51, 51));
        pnQuanlynhansu.setLayout(new java.awt.CardLayout());
        pnMain.add(pnQuanlynhansu, "card3");

        pnInfo.setBackground(new java.awt.Color(0, 102, 102));
        pnInfo.setLayout(new java.awt.CardLayout());
        pnMain.add(pnInfo, "card4");

        pnSetting.setBackground(new java.awt.Color(255, 204, 204));
        pnSetting.setLayout(new java.awt.CardLayout());
        pnMain.add(pnSetting, "card4");

        pnQuanlytuyendung.setBackground(new java.awt.Color(153, 0, 153));
        pnQuanlytuyendung.setLayout(new java.awt.CardLayout());
        pnMain.add(pnQuanlytuyendung, "card4");

        getContentPane().add(pnMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 56, 1386, 838));

        jSeparator9.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 50, -1, 850));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/blue-background-bricks-close-up-colors-of-autumn-2096622.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 9820, 910));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuantriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuantriMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantriMouseClicked
   
    
    void LoadPanel()
    {
        QuanlytuyendungJPanel a = new QuanlytuyendungJPanel();
        a.setVisible(true);
        panels= new ArrayList<>();
        panels.add(this.pnQuantrihethong);
        panels.add(this.pnQuanlynhansu);
        pnQuanlytuyendung.add(a);
        panels.add(pnQuanlytuyendung);
        panels.add(this.pnThongke);
        panels.add(this.pnTrogiup);
        panels.add(this.pnMain_);
        panels.add(this.pnSetting);
        panels.add(this.pnInfo);
        panels.add(this.pnPerson);
    }
    
     void LoadButton()
    {
        BtnList= new ArrayList<>();
        BtnList.add(this.btnQuantri);
        BtnList.add(this.btnQuanlynhansu);
        BtnList.add(this.btnQuanlytuyendung);
        BtnList.add(this.btnThongke);
        BtnList.add(this.btnTrogiup);
        BtnList.add(this.btnLoout);
        BtnList.add(this.btnInfo);
        BtnList.add(this.btnSetting);
    }
     void XuLiBtn()
    {
        for( var x : BtnList)
        {
            x.setUI(new BasicButtonUI());
            x.setBackground(new Color(242,242,242));
        }
    }
    void XuLiBtn(JButton btButton)
    {
        for( var x : BtnList)
        {
            if(btButton == x)
            {
              x.setBackground(Color.white);
              x.setForeground(new Color(140, 194, 230));
            }else
            {
             x.setBackground(new Color(242,242,242));
             x.setForeground(new Color(85,85,85));
            }
        }
    }
    void XuLiPanel(JPanel pnJPanel)
    {
        for( var x : panels)
        {
            if(pnJPanel == x)
            {
                pnJPanel.setVisible(true);
            }else
            x.setVisible(false);
        }
    }
    private void btnQuantriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuantriActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnQuantrihethong);
        XuLiBtn(btnQuantri);
    }//GEN-LAST:event_btnQuantriActionPerformed

    private void btnQuanlynhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlynhansuActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnQuanlynhansu);
        XuLiBtn(btnQuanlynhansu);
    }//GEN-LAST:event_btnQuanlynhansuActionPerformed

    private void btnQuanlytuyendungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuanlytuyendungActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnQuanlytuyendung);
        XuLiBtn(btnQuanlytuyendung);
    }//GEN-LAST:event_btnQuanlytuyendungActionPerformed

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnThongke);
        XuLiBtn(btnThongke);
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void btnTrogiupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrogiupActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnTrogiup);
        XuLiBtn(btnTrogiup);
    }//GEN-LAST:event_btnTrogiupActionPerformed

    private void pnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnMenuMouseClicked
        // TODO add your handling code here:
        
        //XuLiBtn(jButton6);
    }//GEN-LAST:event_pnMenuMouseClicked

    private void lbLogoNhomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbLogoNhomMouseClicked
        // TODO add your handling code here:
        XuLiPanel(pnMain_);
         XuLiBtn();
    }//GEN-LAST:event_lbLogoNhomMouseClicked

    private void btnInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnInfo);
    }//GEN-LAST:event_btnInfoActionPerformed

    private void pnPersonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnPersonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnPersonMouseClicked
    static int i = 1;
    private void pnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUserMouseClicked
        // TODO add your handling code here:
        if (i%2!=0) {
            i++;
            pnPerson.setVisible(true);
            jLabel_.setIcon(new ImageIcon(getClass().getResource("/Img/menu2.png")));
        }else{
            i++;
            pnPerson.setVisible(false);
            jLabel_.setIcon(new ImageIcon(getClass().getResource("/Img/menu.png")));
        }
        
    }//GEN-LAST:event_pnUserMouseClicked

    private void btnSettingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSettingActionPerformed
        // TODO add your handling code here:
        XuLiPanel(pnSetting);
    }//GEN-LAST:event_btnSettingActionPerformed

    private void btnLooutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLooutMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnLooutMouseClicked

    private void btnQuantriFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnQuantriFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuantriFocusGained

    private void btnQuanlynhansuFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnQuanlynhansuFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanlynhansuFocusGained

    private void btnQuanlytuyendungFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnQuanlytuyendungFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanlytuyendungFocusGained

    private void btnThongkeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnThongkeFocusGained
        // TODO add your handling code here
    }//GEN-LAST:event_btnThongkeFocusGained

    private void btnTrogiupFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnTrogiupFocusGained
        // TODO add your handling code 
    }//GEN-LAST:event_btnTrogiupFocusGained

    private void btnLooutFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnLooutFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLooutFocusGained

    private void btnInfoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnInfoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoFocusGained

    private void btnSettingFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSettingFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingFocusGained

    private void btnQuantriFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnQuantriFocusLost
        // TODO add your handling code here:
        //jButton1.setBackground(Color.black);
    }//GEN-LAST:event_btnQuantriFocusLost

    private void btnQuanlynhansuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnQuanlynhansuFocusLost
        // TODO add your handling code here
    }//GEN-LAST:event_btnQuanlynhansuFocusLost

    private void btnQuanlytuyendungFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnQuanlytuyendungFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanlytuyendungFocusLost

    private void btnThongkeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnThongkeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongkeFocusLost

    private void btnTrogiupFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnTrogiupFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTrogiupFocusLost

    private void btnLooutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnLooutFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLooutFocusLost

    private void btnInfoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnInfoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInfoFocusLost

    private void btnSettingFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_btnSettingFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSettingFocusLost

    private void btnQuantriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuantriMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnQuantri);
    }//GEN-LAST:event_btnQuantriMouseEntered

    private void btnQuantriMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuantriMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnQuantriMouseExited

    private void btnQuanlynhansuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanlynhansuMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnQuanlynhansu);
    }//GEN-LAST:event_btnQuanlynhansuMouseEntered

    private void btnQuanlynhansuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanlynhansuMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnQuanlynhansuMouseExited

    private void btnQuanlytuyendungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanlytuyendungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnQuanlytuyendungMouseClicked

    private void btnQuanlytuyendungMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanlytuyendungMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnQuanlytuyendung);
    }//GEN-LAST:event_btnQuanlytuyendungMouseEntered

    private void btnQuanlytuyendungMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQuanlytuyendungMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnQuanlytuyendungMouseExited

    private void btnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnThongke);
    }//GEN-LAST:event_btnThongkeMouseEntered

    private void btnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnThongkeMouseExited

    private void btnTrogiupMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrogiupMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnTrogiup);
    }//GEN-LAST:event_btnTrogiupMouseEntered

    private void btnTrogiupMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrogiupMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnTrogiupMouseExited

    private void btnLooutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLooutMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnLoout);
    }//GEN-LAST:event_btnLooutMouseEntered

    private void btnLooutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLooutMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnLooutMouseExited

    private void btnInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnInfo);
    }//GEN-LAST:event_btnInfoMouseEntered

    private void btnInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnInfoMouseExited

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        // TODO add your handling code here:
        XuLiBtn(btnSetting);
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        // TODO add your handling code here:
        XuLiBtn();
    }//GEN-LAST:event_btnSettingMouseExited

    private void btnInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInfoMouseClicked
        // TODO add your handling code here:
        XuLiPanel(pnInfo);
    }//GEN-LAST:event_btnInfoMouseClicked
    int xMouse;
    int yMouse;
    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked
        // TODO add your handling code here:
        XuLiPanel(pnSetting);
    }//GEN-LAST:event_btnSettingMouseClicked

    private void pnHeadMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHeadMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_pnHeadMousePressed

    private void pnHeadMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHeadMouseDragged
        // TODO add your handling code here
        int x= evt.getXOnScreen();
        int y= evt.getYOnScreen();
       this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_pnHeadMouseDragged

    private void pnUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUserMouseEntered
        // TODO add your handling code here:
        pnUser.setBackground(new Color(13,82,123));
    }//GEN-LAST:event_pnUserMouseEntered

    private void pnUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnUserMouseExited
        // TODO add your handling code here:
        pnUser.setBackground(new Color(87,158,200));
    }//GEN-LAST:event_pnUserMouseExited

    private void btnThongbaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongbaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongbaoActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Linux".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInfo;
    private javax.swing.JButton btnLoout;
    private javax.swing.JButton btnQuanlynhansu;
    private javax.swing.JButton btnQuanlytuyendung;
    private javax.swing.JButton btnQuantri;
    private javax.swing.JButton btnSetting;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongbao;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnTinnhan;
    private javax.swing.JButton btnTrogiup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel_;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lbLogoNhom;
    private javax.swing.JLabel lbName;
    private javax.swing.JLabel lbTimkiem;
    private javax.swing.JPanel pnCopyright;
    private javax.swing.JPanel pnHead;
    private javax.swing.JPanel pnInfo;
    private javax.swing.JPanel pnMain;
    private javax.swing.JPanel pnMain_;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnPerson;
    private javax.swing.JPanel pnQuanlynhansu;
    private javax.swing.JPanel pnQuanlytuyendung;
    private javax.swing.JPanel pnQuantrihethong;
    private javax.swing.JPanel pnSetting;
    private javax.swing.JPanel pnThongke;
    private javax.swing.JPanel pnTimkiemHien;
    private javax.swing.JPanel pnTrogiup;
    private javax.swing.JPanel pnUser;
    private javax.swing.JTextField txtTimkiemAn;
    // End of variables declaration//GEN-END:variables
}
