/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Color;

/**
 *
 * @author DELL
 */
public class ProfileJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel2
     */
    public ProfileJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnDangKi = new javax.swing.JPanel();
        pnPhongBan = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTenNhanVien = new javax.swing.JTextField();
        txtNhanVien = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtCMND = new javax.swing.JTextField();
        txtQueQuan = new javax.swing.JTextField();
        RadioBtnNam = new javax.swing.JRadioButton();
        RadioBntNu = new javax.swing.JRadioButton();
        RadioBtnGioiTinhKhac = new javax.swing.JRadioButton();
        DateChooseNgaySinh = new com.toedter.calendar.JDateChooser();
        jPanelMaNhanVIen = new javax.swing.JPanel();
        jPanelTenNhanVien = new javax.swing.JPanel();
        jPanelDiaChi = new javax.swing.JPanel();
        jPanelSoDienThoai = new javax.swing.JPanel();
        jPanelNoiSinh = new javax.swing.JPanel();
        jPanelGioiTinh = new javax.swing.JPanel();
        jPanelCMND = new javax.swing.JPanel();
        jPanelQueQuan = new javax.swing.JPanel();
        jPanelDanToc = new javax.swing.JPanel();
        jPanelNgaySinh = new javax.swing.JPanel();
        txtDanToc = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnChucVu = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnHinhAnh = new javax.swing.JPanel();
        lbThemHinhAnh = new javax.swing.JLabel();
        txtMaChucVu = new javax.swing.JTextField();
        txtTenChucVu = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pbtable = new javax.swing.JPanel();
        jScrollPaneNhanVien = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jScrollPaneChucVu = new javax.swing.JScrollPane();
        tblChucVu = new javax.swing.JTable();
        jScrollPanePhongBan = new javax.swing.JScrollPane();
        tblPhongBan = new javax.swing.JTable();
        pnhead = new javax.swing.JPanel();
        btnNhanVien = new javax.swing.JButton();
        btnPhongBan = new javax.swing.JButton();
        btnChucVu = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        pnController = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();
        bntSapXep = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1386, 838));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnDangKi.setLayout(new java.awt.CardLayout());

        pnPhongBan.setBackground(new java.awt.Color(255, 255, 255));
        pnPhongBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        pnPhongBan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton6.setBackground(new java.awt.Color(0, 171, 82));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Previous");
        jButton6.setBorderPainted(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        pnPhongBan.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 330, 50));

        jPanel5.setBackground(new java.awt.Color(0, 171, 82));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("PHÒNG BAN");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnPhongBan.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        pnDangKi.add(pnPhongBan, "card3");

        pnNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        pnNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 204, 0)));
        pnNhanVien.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Giới Tính");
        pnNhanVien.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Nơi Sinh");
        pnNhanVien.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 110, 30));

        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(153, 153, 153));
        jTextField5.setText("Không được để trống");
        jTextField5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 250, -1));

        txtSoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtSoDienThoai.setForeground(new java.awt.Color(153, 153, 153));
        txtSoDienThoai.setText("Không được để trống");
        txtSoDienThoai.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 250, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Số Điện Thoại");
        pnNhanVien.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, -1));

        txtDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtDiaChi.setForeground(new java.awt.Color(153, 153, 153));
        txtDiaChi.setText("Không được để trống");
        txtDiaChi.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 250, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Địa Chỉ");
        pnNhanVien.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 110, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Tên Nhân Viên");
        pnNhanVien.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, -1));

        txtTenNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtTenNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        txtTenNhanVien.setText("Không được để trống");
        txtTenNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 250, -1));

        txtNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtNhanVien.setForeground(new java.awt.Color(153, 153, 153));
        txtNhanVien.setText("Không được để trống");
        txtNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 250, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Mã Nhân Viên");
        pnNhanVien.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 45, 90, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Chứng Minh Nhân Dân");
        pnNhanVien.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 170, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quê Quán");
        pnNhanVien.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 90, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Dân Tộc");
        pnNhanVien.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 100, -1));

        txtCMND.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtCMND.setForeground(new java.awt.Color(153, 153, 153));
        txtCMND.setText("Không được để trống");
        txtCMND.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 250, -1));

        txtQueQuan.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtQueQuan.setForeground(new java.awt.Color(204, 204, 204));
        txtQueQuan.setText("Không được để trống");
        txtQueQuan.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 250, -1));

        RadioBtnNam.setBackground(new java.awt.Color(255, 255, 255));
        RadioBtnNam.setForeground(new java.awt.Color(153, 153, 153));
        RadioBtnNam.setText("Nam");
        pnNhanVien.add(RadioBtnNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, 20));

        RadioBntNu.setBackground(new java.awt.Color(255, 255, 255));
        RadioBntNu.setForeground(new java.awt.Color(153, 153, 153));
        RadioBntNu.setText("Nữ");
        pnNhanVien.add(RadioBntNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, -1, 20));

        RadioBtnGioiTinhKhac.setBackground(new java.awt.Color(255, 255, 255));
        RadioBtnGioiTinhKhac.setForeground(new java.awt.Color(153, 153, 153));
        RadioBtnGioiTinhKhac.setText("Giới Tính Khác");
        pnNhanVien.add(RadioBtnGioiTinhKhac, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 100, 20));

        DateChooseNgaySinh.setBackground(new java.awt.Color(255, 255, 255));
        pnNhanVien.add(DateChooseNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 270, -1));

        jPanelMaNhanVIen.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelMaNhanVIenLayout = new javax.swing.GroupLayout(jPanelMaNhanVIen);
        jPanelMaNhanVIen.setLayout(jPanelMaNhanVIenLayout);
        jPanelMaNhanVIenLayout.setHorizontalGroup(
            jPanelMaNhanVIenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelMaNhanVIenLayout.setVerticalGroup(
            jPanelMaNhanVIenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelMaNhanVIen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 280, 2));

        jPanelTenNhanVien.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelTenNhanVienLayout = new javax.swing.GroupLayout(jPanelTenNhanVien);
        jPanelTenNhanVien.setLayout(jPanelTenNhanVienLayout);
        jPanelTenNhanVienLayout.setHorizontalGroup(
            jPanelTenNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelTenNhanVienLayout.setVerticalGroup(
            jPanelTenNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelTenNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 280, 2));

        jPanelDiaChi.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelDiaChiLayout = new javax.swing.GroupLayout(jPanelDiaChi);
        jPanelDiaChi.setLayout(jPanelDiaChiLayout);
        jPanelDiaChiLayout.setHorizontalGroup(
            jPanelDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDiaChiLayout.setVerticalGroup(
            jPanelDiaChiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, 2));

        jPanelSoDienThoai.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelSoDienThoaiLayout = new javax.swing.GroupLayout(jPanelSoDienThoai);
        jPanelSoDienThoai.setLayout(jPanelSoDienThoaiLayout);
        jPanelSoDienThoaiLayout.setHorizontalGroup(
            jPanelSoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSoDienThoaiLayout.setVerticalGroup(
            jPanelSoDienThoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelSoDienThoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 280, 2));

        jPanelNoiSinh.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelNoiSinhLayout = new javax.swing.GroupLayout(jPanelNoiSinh);
        jPanelNoiSinh.setLayout(jPanelNoiSinhLayout);
        jPanelNoiSinhLayout.setHorizontalGroup(
            jPanelNoiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelNoiSinhLayout.setVerticalGroup(
            jPanelNoiSinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelNoiSinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 280, 2));

        jPanelGioiTinh.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelGioiTinhLayout = new javax.swing.GroupLayout(jPanelGioiTinh);
        jPanelGioiTinh.setLayout(jPanelGioiTinhLayout);
        jPanelGioiTinhLayout.setHorizontalGroup(
            jPanelGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelGioiTinhLayout.setVerticalGroup(
            jPanelGioiTinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelGioiTinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 280, 2));

        jPanelCMND.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelCMNDLayout = new javax.swing.GroupLayout(jPanelCMND);
        jPanelCMND.setLayout(jPanelCMNDLayout);
        jPanelCMNDLayout.setHorizontalGroup(
            jPanelCMNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelCMNDLayout.setVerticalGroup(
            jPanelCMNDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelCMND, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 280, 2));

        jPanelQueQuan.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelQueQuanLayout = new javax.swing.GroupLayout(jPanelQueQuan);
        jPanelQueQuan.setLayout(jPanelQueQuanLayout);
        jPanelQueQuanLayout.setHorizontalGroup(
            jPanelQueQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelQueQuanLayout.setVerticalGroup(
            jPanelQueQuanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 280, 2));

        jPanelDanToc.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelDanTocLayout = new javax.swing.GroupLayout(jPanelDanToc);
        jPanelDanToc.setLayout(jPanelDanTocLayout);
        jPanelDanTocLayout.setHorizontalGroup(
            jPanelDanTocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelDanTocLayout.setVerticalGroup(
            jPanelDanTocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelDanToc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 280, 2));

        jPanelNgaySinh.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout jPanelNgaySinhLayout = new javax.swing.GroupLayout(jPanelNgaySinh);
        jPanelNgaySinh.setLayout(jPanelNgaySinhLayout);
        jPanelNgaySinhLayout.setHorizontalGroup(
            jPanelNgaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelNgaySinhLayout.setVerticalGroup(
            jPanelNgaySinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanelNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 280, 2));

        txtDanToc.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtDanToc.setForeground(new java.awt.Color(153, 153, 153));
        txtDanToc.setText("Không được để trống");
        txtDanToc.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnNhanVien.add(txtDanToc, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 240, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Ngày Sinh");
        pnNhanVien.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 100, -1));

        btnNext.setBackground(new java.awt.Color(0, 171, 82));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 255));
        btnNext.setText("Next");
        btnNext.setBorderPainted(false);
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        pnNhanVien.add(btnNext, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 330, 50));

        jPanel3.setBackground(new java.awt.Color(0, 171, 82));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NHÂN VIÊN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );

        pnNhanVien.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        pnDangKi.add(pnNhanVien, "card2");

        pnChucVu.setBackground(new java.awt.Color(255, 255, 255));
        pnChucVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 0)));
        pnChucVu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton7.setBackground(new java.awt.Color(0, 171, 82));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Previous");
        jButton7.setBorderPainted(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        pnChucVu.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 160, 50));

        jButton4.setBackground(new java.awt.Color(0, 171, 82));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Next");
        jButton4.setBorderPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        pnChucVu.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 570, 160, 50));

        jPanel4.setBackground(new java.awt.Color(0, 171, 82));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("CHỨC VỤ");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnChucVu.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));

        pnHinhAnh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 82), 4));
        pnHinhAnh.setLayout(new java.awt.CardLayout());
        pnHinhAnh.add(lbThemHinhAnh, "card2");

        pnChucVu.add(pnHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 260, 230));

        txtMaChucVu.setForeground(new java.awt.Color(102, 102, 102));
        txtMaChucVu.setText("Không được để trống");
        txtMaChucVu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnChucVu.add(txtMaChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 378, 240, 20));

        txtTenChucVu.setForeground(new java.awt.Color(102, 102, 102));
        txtTenChucVu.setText("Không được để trống");
        txtTenChucVu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnChucVu.add(txtTenChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 448, 240, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setText("Mã Chức Vụ");
        pnChucVu.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("Tên Chức Vụ");
        pnChucVu.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, 20));

        jPanel7.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        pnChucVu.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 270, 3));

        jPanel8.setBackground(new java.awt.Color(0, 204, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );

        pnChucVu.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 270, 3));

        jButton1.setBackground(new java.awt.Color(0, 171, 82));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.setBorderPainted(false);
        pnChucVu.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 130, -1));

        jButton2.setBackground(new java.awt.Color(0, 171, 82));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Xóa");
        jButton2.setBorderPainted(false);
        pnChucVu.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 130, -1));

        pnDangKi.add(pnChucVu, "card3");

        add(pnDangKi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, 330, 840));

        pbtable.setLayout(new java.awt.CardLayout());

        tblNhanVien.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 82)));
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Nhân Viên", "Tên Nhân Viên", "Số Điện Thoại", "Ngày Sinh"
            }
        ));
        tblNhanVien.setGridColor(new java.awt.Color(255, 255, 255));
        tblNhanVien.setSelectionBackground(new java.awt.Color(0, 171, 82));
        jScrollPaneNhanVien.setViewportView(tblNhanVien);

        pbtable.add(jScrollPaneNhanVien, "card2");

        tblChucVu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 82)));
        tblChucVu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Chức Vụ", "Tên Chức Vụ"
            }
        ));
        tblChucVu.setGridColor(new java.awt.Color(255, 255, 255));
        tblChucVu.setSelectionBackground(new java.awt.Color(0, 171, 82));
        jScrollPaneChucVu.setViewportView(tblChucVu);

        pbtable.add(jScrollPaneChucVu, "card2");

        tblPhongBan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 82)));
        tblPhongBan.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblPhongBan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phòng Ban", "Tên Phòng Ban", "Trưởng Phòng"
            }
        ));
        tblPhongBan.setGridColor(new java.awt.Color(255, 255, 255));
        tblPhongBan.setSelectionBackground(new java.awt.Color(0, 171, 82));
        jScrollPanePhongBan.setViewportView(tblPhongBan);

        pbtable.add(jScrollPanePhongBan, "card2");

        add(pbtable, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1060, 640));

        pnhead.setBackground(new java.awt.Color(0, 171, 82));
        pnhead.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 171, 82)));
        pnhead.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNhanVien.setBackground(new java.awt.Color(0, 171, 82));
        btnNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnNhanVien.setText("NHÂN VIÊN");
        btnNhanVien.setBorderPainted(false);
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseExited(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        pnhead.add(btnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, 40));

        btnPhongBan.setBackground(new java.awt.Color(0, 171, 82));
        btnPhongBan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnPhongBan.setForeground(new java.awt.Color(255, 255, 255));
        btnPhongBan.setText("PHÒNG BAN");
        btnPhongBan.setBorderPainted(false);
        btnPhongBan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPhongBanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPhongBanMouseExited(evt);
            }
        });
        btnPhongBan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPhongBanActionPerformed(evt);
            }
        });
        pnhead.add(btnPhongBan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 180, 40));

        btnChucVu.setBackground(new java.awt.Color(0, 171, 82));
        btnChucVu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnChucVu.setForeground(new java.awt.Color(255, 255, 255));
        btnChucVu.setText("CHỨC VỤ");
        btnChucVu.setBorderPainted(false);
        btnChucVu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChucVuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChucVuMouseExited(evt);
            }
        });
        btnChucVu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChucVuActionPerformed(evt);
            }
        });
        pnhead.add(btnChucVu, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 190, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("QUẢN LÍ NHÂN SỰ");
        pnhead.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 200, 50));

        add(pnhead, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 100));

        pnController.setBackground(new java.awt.Color(255, 255, 255));

        btnThem.setBackground(new java.awt.Color(0, 171, 82));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnThem.setBorderPainted(false);

        btnXoa.setBackground(new java.awt.Color(0, 171, 82));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 255));
        btnXoa.setText("Xóa");
        btnXoa.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnXoa.setBorderPainted(false);
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(0, 171, 82));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSua.setBorderPainted(false);

        btnTimKiem.setBackground(new java.awt.Color(0, 171, 82));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnTimKiem.setBorderPainted(false);

        bntSapXep.setBackground(new java.awt.Color(0, 171, 82));
        bntSapXep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bntSapXep.setForeground(new java.awt.Color(255, 255, 255));
        bntSapXep.setText("Sắp Sếp");
        bntSapXep.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        bntSapXep.setBorderPainted(false);

        javax.swing.GroupLayout pnControllerLayout = new javax.swing.GroupLayout(pnController);
        pnController.setLayout(pnControllerLayout);
        pnControllerLayout.setHorizontalGroup(
            pnControllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControllerLayout.createSequentialGroup()
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(bntSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 503, Short.MAX_VALUE))
        );
        pnControllerLayout.setVerticalGroup(
            pnControllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnControllerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnControllerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bntSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        add(pnController, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 740, 1060, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        pnChucVu.setVisible(true);
        pnNhanVien.setVisible(false);
        pnPhongBan.setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        pnChucVu.setVisible(true);
        pnNhanVien.setVisible(false);
        pnPhongBan.setVisible(false);
    }//GEN-LAST:event_btnNextActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        pnChucVu.setVisible(false);
        pnNhanVien.setVisible(true);
        pnPhongBan.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        pnChucVu.setVisible(false);
        pnNhanVien.setVisible(false);
        pnPhongBan.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnNhanVienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseEntered
        // TODO add your handling code here:
        btnNhanVien.setBackground(new Color(85, 199, 139));
        btnChucVu.setBackground(new Color(0, 171, 82));
        btnPhongBan.setBackground(new Color(0, 171, 82));
    }//GEN-LAST:event_btnNhanVienMouseEntered

    private void btnNhanVienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseExited
        // TODO add your handling code here:
        btnNhanVien.setBackground(new Color(0, 171, 82));
        btnChucVu.setBackground(new Color(0, 171, 82));
        btnPhongBan.setBackground(new Color(0, 171, 82));
    }//GEN-LAST:event_btnNhanVienMouseExited

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
        jScrollPaneNhanVien.setVisible(true);
        jScrollPaneChucVu.setVisible(false);
        jScrollPanePhongBan.setVisible(false);
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnPhongBanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongBanMouseEntered
        btnNhanVien.setBackground(new Color(0, 171, 82));
        btnChucVu.setBackground(new Color(0, 171, 82));
        btnPhongBan.setBackground(new Color(85, 199, 139));
    }//GEN-LAST:event_btnPhongBanMouseEntered

    private void btnPhongBanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPhongBanMouseExited
        // TODO add your handling code here:
        btnNhanVien.setBackground(new Color(0, 171, 82));
        btnChucVu.setBackground(new Color(0, 171, 82));
        btnPhongBan.setBackground(new Color(0, 171, 82));
    }//GEN-LAST:event_btnPhongBanMouseExited

    private void btnPhongBanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPhongBanActionPerformed
        // TODO add your handling code here:
        jScrollPaneNhanVien.setVisible(false);
        jScrollPaneChucVu.setVisible(false);
        jScrollPanePhongBan.setVisible(true);
    }//GEN-LAST:event_btnPhongBanActionPerformed

    private void btnChucVuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChucVuMouseEntered
        btnNhanVien.setBackground(new Color(0, 171, 82));
        btnChucVu.setBackground(new Color(85, 199, 139));
        btnPhongBan.setBackground(new Color(0, 171, 82));
    }//GEN-LAST:event_btnChucVuMouseEntered

    private void btnChucVuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChucVuMouseExited
        // TODO add your handling code here:
        btnNhanVien.setBackground(new Color(0, 171, 82));
        btnChucVu.setBackground(new Color(0, 171, 82));
        btnPhongBan.setBackground(new Color(0, 171, 82));
    }//GEN-LAST:event_btnChucVuMouseExited

    private void btnChucVuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChucVuActionPerformed
        // TODO add your handling code here:
        jScrollPaneNhanVien.setVisible(false);
        jScrollPaneChucVu.setVisible(true);
        jScrollPanePhongBan.setVisible(false);
    }//GEN-LAST:event_btnChucVuActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser DateChooseNgaySinh;
    private javax.swing.JRadioButton RadioBntNu;
    private javax.swing.JRadioButton RadioBtnGioiTinhKhac;
    private javax.swing.JRadioButton RadioBtnNam;
    private javax.swing.JButton bntSapXep;
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnPhongBan;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCMND;
    private javax.swing.JPanel jPanelDanToc;
    private javax.swing.JPanel jPanelDiaChi;
    private javax.swing.JPanel jPanelGioiTinh;
    private javax.swing.JPanel jPanelMaNhanVIen;
    private javax.swing.JPanel jPanelNgaySinh;
    private javax.swing.JPanel jPanelNoiSinh;
    private javax.swing.JPanel jPanelQueQuan;
    private javax.swing.JPanel jPanelSoDienThoai;
    private javax.swing.JPanel jPanelTenNhanVien;
    private javax.swing.JScrollPane jScrollPaneChucVu;
    private javax.swing.JScrollPane jScrollPaneNhanVien;
    private javax.swing.JScrollPane jScrollPanePhongBan;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel lbThemHinhAnh;
    private javax.swing.JPanel pbtable;
    private javax.swing.JPanel pnChucVu;
    private javax.swing.JPanel pnController;
    private javax.swing.JPanel pnDangKi;
    private javax.swing.JPanel pnHinhAnh;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnPhongBan;
    private javax.swing.JPanel pnhead;
    private javax.swing.JTable tblChucVu;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTable tblPhongBan;
    private javax.swing.JTextField txtCMND;
    private javax.swing.JTextField txtDanToc;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtMaChucVu;
    private javax.swing.JTextField txtNhanVien;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSoDienThoai;
    private javax.swing.JTextField txtTenChucVu;
    private javax.swing.JTextField txtTenNhanVien;
    // End of variables declaration//GEN-END:variables
}
